name: Nightly Build

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  build-and-release:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10'

      - name: Restore dependencies
        run: dotnet restore "Steam Desktop Authenticator.sln"

      - name: Build project
        run: dotnet build "Steam Desktop Authenticator.sln" --configuration Release --no-restore

      - name: Publish project
        run: |
          dotnet publish "Steam Desktop Authenticator/Steam Desktop Authenticator.csproj" `
            --configuration Release `
            --output ./publish

      - name: Archive production assets
        run: Compress-Archive -Path ./publish/* -DestinationPath SDA-nightly.zip

      - name: Create or Update Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly Build
          body: |
            🧪 Automated nightly build. This release is updated frequently and may be unstable.

            **重要:** 运行此程序前，您必须先在您的 Windows 电脑上安装 [.NET 10 Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/10.0/runtime?runtime=desktop)。
          prerelease: true
          files: SDA-nightly.zip
